name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Install PyInstaller (dev)
        run: uv run pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          uv run pyinstaller --noconfirm --onefile --windowed --icon=src\img\icon.ico --name CamRenamer src/main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: CamRenamer-exe
          path: dist/CamRenamer.exe
